# NOTE: update this with your service name
service: vote

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-votes
  #  tableName2: ${self:custom.stage}-userVoterGroup
  # Set our DynamoDB throughput for prod and all other non-prod stages.
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #  environment: ${file(env.yml):${self:provider.stage}}

  #   These environment variables are made available to our functions
  #   under process.env.
  environment:
    tableName: ${self:custom.tableName}
  #    tableName2: ${self:custom.tableName2}

  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:DescribeTable
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    - dynamodb:BatchGetItem
    #    # Restrict our IAM role permissions to
    #    # the specific table for the stage
    Resource:
    - "Fn::GetAtt": [ Votes, Arn ]
    - Fn::Join:
      - "/"
      -
        - { "Fn::GetAtt": [Votes, Arn ] }
        - "index/*"
#    - "Fn::GetAtt": [ UserVoterGroupTable, Arn ]

functions:
  castVote:
    handler: castVote.main
    events:
    - http:
        path: castVote
        method: post
        cors: true
        authorizer: aws_iam

  getVote:
    handler: getVote.main
    events:
    - http:
        path: getVote
        method: post
        cors: true
        authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
# API Gateway Errors
- ${file(resources/api-gateway-errors.yml)}
# DynamoDB
- ${file(resources/dynamodb-table.yml)}
